filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
build:
  nodes:
    php71:
      environment:
        php: 7.1
    php72:
      environment:
        php: 7.2
    php73:
      environment:
        php: 7.3
    php74:
      environment:
        php: 7.4
    coverage:
      tests:
        override:
          - command: 'XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=phpunit-coverage.xml'
            coverage:
              file: 'phpunit-coverage.xml'
              format: 'php-clover'
    analysis:
      tests:
        override:
          - command: phpcs-run
            use_website_config: true
          - php-scrutinizer-run
  tests:
    override:
      - command: 'vendor/bin/phpunit'
